### ISSUE TITLE
Failed to connect to ComfyUI

### ISSUE THREAD

**Issue by PERRETJonatan** [jtyszkiew/ImageSmith#1]
Hello,

I followed the README and for the authentication, i put blank, my instance is open for local access.
In the README, it says to start imagesmith.py, but it's not at the root level of the project. So i start the main.py but I get `Failed to connect to ComfyUI: Failed to connect to any ComfyUI instance`.

any help ?

**Comment by jtyszkiew** [comment]
Ahhh, sorry, I forgot to change it in readme, I will fix it later.

Can you provide your configuration file with the `instances` section?

**Comment by PERRETJonatan** [comment]
sure, here it is.

```
instances:
    - url: 'http://localhost:8188/'
      weight: 2  # Higher weight means more traffic
      auth:
        # Basic authentication
        username: ""
        password: ""
        # SSL/TLS settings
        ssl_verify: false
        ssl_cert: "/path/to/cert.pem"  # Optional
  input_dir: /path/to/output
```

**Comment by jtyszkiew** [comment]
Please try it like this:
```
comfyui:
  instances:
    - url: 'http://127.0.0.1:8188'
      auth:
        ssl_verify: false
      weight: 1
```

I understand this might be confusing, but I didn't have enough time to provide full specification yet. Working on some more detailed documentation. This one should work, since it's exact the same I'm using.
